title: "Benei's Portfolio"
description: "My personal portfolio showcasing projects, blog posts, and experiments."
author: "Benei"
# Use GitHub Pages-supported theme. Remove/change if you have custom styling.
theme: minima

# (Optional) social links displayed by the theme
social_links:
  - name: GitHub
    url: https://github.com/Benei
  - name: LinkedIn
    url: https://linkedin.com/in/Benei

# Build settings
markdown: kramdown
permalink: pretty

# Pages to appear in the site navigation
header_pages:
  - index.md
  - projects.md
  - about.md 