title: "Benei's Portfolio"
description: "My personal portfolio showcasing projects, blog posts, and experiments."
author: "Benei"
# Use GitHub Pages-supported theme. Remove/change if you have custom styling.
# Supply theme replaces Minima
remote_theme: "CloudCannon/vonge-jekyll-bookshop-template"

# Custom assets (will be referenced in override includes)
custom_css: "/assets/css/custom.css"
# custom_js: "/assets/js/dark-mode.js"

# (Optional) social links displayed by the theme
social_links:
  - name: GitHub
    url: https://github.com/Benei
  - name: LinkedIn
    url: https://linkedin.com/in/Benei

# Build settings
markdown: kramdown
permalink: pretty

# Pages to appear in the site navigation
header_pages:
  - index.md
  - projects.md
  - about.md 